In [1]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine(
    "mysql+pymysql://root:shlasr11@localhost/security_lab?unix_socket=/tmp/mysql.sock"
)

query = "SELECT * FROM auth_events"

df = pd.read_sql(query, engine)

df

,id,timestamp,host,user,ip,action,status
0,1,2026-04-05 10:00:00,server1,root,10.0.0.5,login,failed
1,2,2026-04-05 10:01:00,server1,root,10.0.0.5,login,failed
2,3,2026-04-05 10:02:00,server1,root,10.0.0.5,login,failed
3,4,2026-04-05 10:04:00,server1,root,10.0.0.5,login,success
4,5,2026-04-05 10:06:00,server1,root,NaN,sudo,NaN
5,6,2026-04-05 10:07:00,server1,root,NaN,create_user,NaN
6,7,2026-04-05 11:00:00,server2,admin,192.168.1.8,login,failed
7,8,2026-04-05 11:10:00,server2,admin,192.168.1.8,login,success
8,9,2026-04-05 12:00:00,server1,ubuntu,10.0.0.9,login,failed
9,10,2026-04-05 12:01:00,server1,ubuntu,10.0.0.9,login,success
10,11,2026-04-05 13:00:00,server3,ec2-user,54.12.33.21,login,failed
11,12,2026-04-05 13:01:00,server3,ec2-user,54.12.33.21,login,failed
12,13,2026-04-05 13:02:00,server3,ec2-user,54.12.33.21,login,failed
13,14,2026-04-05 13:04:00,server3,ec2-user,54.12.33.21,login,success
14,15,2026-04-05 13:05:00,server3,ec2-user,NaN,sudo,NaN

In [8]:
df[df["status"] == "failed"]

    id           timestamp     host      user           ip action  status
0    1 2026-04-05 10:00:00  server1      root     10.0.0.5  login  failed
1    2 2026-04-05 10:01:00  server1      root     10.0.0.5  login  failed
2    3 2026-04-05 10:02:00  server1      root     10.0.0.5  login  failed
6    7 2026-04-05 11:00:00  server2     admin  192.168.1.8  login  failed
8    9 2026-04-05 12:00:00  server1    ubuntu     10.0.0.9  login  failed
10  11 2026-04-05 13:00:00  server3  ec2-user  54.12.33.21  login  failed
11  12 2026-04-05 13:01:00  server3  ec2-user  54.12.33.21  login  failed
12  13 2026-04-05 13:02:00  server3  ec2-user  54.12.33.21  login  failed

In [9]:
df[df["status"] == "failed"]["ip"].value_counts()

ip
10.0.0.5       3
54.12.33.21    3
192.168.1.8    1
10.0.0.9       1
Name: count, dtype: int64

In [28]:
failed_events = df[df["status"] == "failed"]
failed_counts = failed_events["ip"].value_counts()
suspicious_ip = failed_counts[failed_counts >= 3]
suspicious_ip

The history saving thread hit an unexpected error (RuntimeError('release unlocked lock')).History will not be written to the database.

ip
10.0.0.5       3
54.12.33.21    3
Name: count, dtype: int64

In [9]:
import json
alerts = []

time_window = pd.Timedelta(minutes=15)

for host, group in df.groupby("host"):

    group = group.sort_values("timestamp").reset_index(drop=True)
    for i in range(len(group)):

        event = group.iloc[i]

        if event["status"] != "failed":
            continue
            
        failed_count = 1
        attack_ip = event["ip"]
        attack_user = event["user"]
        start_time = event["timestamp"]

        for j in range(i + 1, len(group)):

            next_event = group.iloc[j]
            
            if next_event["timestamp"] > start_time + time_window:
                break

            if next_event["status"] == "failed" and next_event["ip"] == attack_ip and next_event["user"] == attack_user:
                failed_count += 1
                continue

            if failed_count >= 3 and next_event["status"] == "success" and next_event["ip"] == attack_ip and next_event["user"] == attack_user:
                
                success_time = next_event["timestamp"]
                for k in range(j + 1, len(group)):
                    
                    sudo_event = group.iloc[k]
                    if sudo_event["timestamp"] > success_time + time_window:
                        break
                    
                    if sudo_event["action"] == "sudo" and sudo_event["user"] == attack_user:
                        
                        sudo_time = sudo_event["timestamp"]
                        for m in range(k + 1, len(group)):
                            create_user_event = group.iloc[m]
    
                            if create_user_event["timestamp"] > sudo_time + time_window:
                                break
                                
                            if create_user_event["action"] == "create_user" and create_user_event["user"] == attack_user:
                                alerts.append({
                                    "host": host,
                                    "ip": attack_ip,
                                    "user": attack_user,
                                    "severity": "HIGH",
                                    "attack_chain":
                                    "failed×3 → success → sudo → create user"
                            })

                        break

output_data = {
    "total_alerts": len(alerts),
    "alerts": alerts
}

with open("outputs/alerts_from_linux_auth.json", "w") as f:
    json.dump(output_data, f, indent=2)
alerts

[{'host': 'server1',
  'ip': '10.0.0.5',
  'user': 'root',
  'severity': 'HIGH',
  'attack_chain': 'failed×3 → success → sudo → create user'}]